update  SEC_EXPRESSION
set value = 'create,edit,search,view,print'
 WHERE PERMISSION_ID = 28 AND ATTRIBUTE = 'action';

update  SEC_EXPRESSION
set value = 'MATCH,MATCH_STATUS,GUANLAN,DEPOT,SYSTEM_PARAMETER,CITY,COMPANY_USER,MATCH_ADDITIONAL_FEE,MATCH_CONTAINER_NO,CONTAINER_TYPE,TRAILER_TYPE,SYSTEM_MAINTENANCE,CARGO_CATEGORY,SHIPPING_LINE,DELIVERY_TIME_SLOT,DELIVERY_TIME,DOCUMENT,REASON_CODE,PACKAGE_UOM,ADDITIONAL_FEE,AUTO_MATCH,DELIVERY_REQUEST,CONTAINER_INVENTORY,MATCH_ADDITIONAL_FEE,ZONE,MANAGEMENT_REPORT,LOCATION,BILLING,MATCH,COMPANY_REGISTRATION,TRUCKER,TRUCK_CAPACITY,COMPANY_USER,DEPOT'
 WHERE PERMISSION_ID = 25 AND ATTRIBUTE = 'document_type';

commit;


