ALTER TABLE ADDITIONAL_FEE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);              
ALTER TABLE CARGO_CATEGORY ADD (MODIFY_DATE DATE DEFAULT SYSDATE);              
ALTER TABLE CITY_DATA ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                   
ALTER TABLE COMPANY_PROFILE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);             
ALTER TABLE CONTAINER_TYPE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);              
ALTER TABLE DELIVERY_PRICE_FEE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);          
ALTER TABLE DELIVERY_REQUESET_ADDFEE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);    
ALTER TABLE DELIVERY_REQUEST ADD (MODIFY_DATE DATE DEFAULT SYSDATE);            
ALTER TABLE DELIVERY_TIME ADD (MODIFY_DATE DATE DEFAULT SYSDATE);               
ALTER TABLE DELIVERY_TIME_SLOT ADD (MODIFY_DATE DATE DEFAULT SYSDATE);          
ALTER TABLE DEPOT_DATA ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                  
ALTER TABLE DOCUMENT_NEED ADD (MODIFY_DATE DATE DEFAULT SYSDATE);               
ALTER TABLE DOCUMENT_RECEIVING_STATUS ADD (MODIFY_DATE DATE DEFAULT SYSDATE);   
ALTER TABLE ERROR_CODE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                  
ALTER TABLE GROUP_FUNCTION ADD (MODIFY_DATE DATE DEFAULT SYSDATE);              
ALTER TABLE GROUP_PROFILE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);               
ALTER TABLE INVENTORY_DAILY ADD (MODIFY_DATE DATE DEFAULT SYSDATE);             
ALTER TABLE INVOICE_DATA ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                
ALTER TABLE INVOICE_DETAIL_DATA ADD (MODIFY_DATE DATE DEFAULT SYSDATE);         
ALTER TABLE INVOICE_PAYMENT_HISTORY ADD (MODIFY_DATE DATE DEFAULT SYSDATE);     
ALTER TABLE MATCH_CAPACITY_REQUEST ADD (MODIFY_DATE DATE DEFAULT SYSDATE);      
ALTER TABLE MATCH_FEE_DETAIL ADD (MODIFY_DATE DATE DEFAULT SYSDATE);            
ALTER TABLE PACKAGE_UOM ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                 
ALTER TABLE PLAN_TABLE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                  
ALTER TABLE REASON_CODE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                 
ALTER TABLE SEC_ATTRIBUTE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);               
ALTER TABLE SEC_ATTRIBUTE_VALUE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);         
ALTER TABLE SEC_DOMAIN ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                  
ALTER TABLE SEC_EXPRESSION ADD (MODIFY_DATE DATE DEFAULT SYSDATE);              
ALTER TABLE SEC_EXTERNAL_GROUP_MEMBERSHIP ADD (MODIFY_DATE DATE DEFAULT SYSDATE)
;                                                                               
                                                                                
ALTER TABLE SEC_GROUP_DETAILS ADD (MODIFY_DATE DATE DEFAULT SYSDATE);           
ALTER TABLE SEC_GROUP_MEMBERSHIP ADD (MODIFY_DATE DATE DEFAULT SYSDATE);        
ALTER TABLE SEC_OPERATOR ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                
ALTER TABLE SEC_PERMISSION ADD (MODIFY_DATE DATE DEFAULT SYSDATE);              
ALTER TABLE SEC_USER_DETAILS ADD (MODIFY_DATE DATE DEFAULT SYSDATE);            
ALTER TABLE SEC_USER_PERSON_RELATIONSHIP ADD (MODIFY_DATE DATE DEFAULT SYSDATE);
ALTER TABLE SHIPPINGLINE_CONTAINER ADD (MODIFY_DATE DATE DEFAULT SYSDATE);      
ALTER TABLE SHIPPING_LINE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);               
ALTER TABLE STATEMENT_DATA ADD (MODIFY_DATE DATE DEFAULT SYSDATE);              
ALTER TABLE STATEMENT_DETAIL_DATA ADD (MODIFY_DATE DATE DEFAULT SYSDATE);       
ALTER TABLE SYSTEM_FUNCTION ADD (MODIFY_DATE DATE DEFAULT SYSDATE);             
ALTER TABLE SYSTEM_PROCESS_PARAMETER ADD (MODIFY_DATE DATE DEFAULT SYSDATE);    
ALTER TABLE TEST_DATA ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                   
ALTER TABLE TRADING_PARTNER ADD (MODIFY_DATE DATE DEFAULT SYSDATE);             
ALTER TABLE TRAILER_TYPE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                
ALTER TABLE TRANSACTION_CODE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);            
ALTER TABLE TRANSACTION_LOG ADD (MODIFY_DATE DATE DEFAULT SYSDATE);             
ALTER TABLE TRUCKER_DATA ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                
ALTER TABLE TRUCKER_DOCUMENT ADD (MODIFY_DATE DATE DEFAULT SYSDATE);            
ALTER TABLE TRUCK_CAPACITY ADD (MODIFY_DATE DATE DEFAULT SYSDATE);              
ALTER TABLE TRUCK_CAPACITY_ADDFEE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);       
ALTER TABLE USER_PROFILE ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                
ALTER TABLE ZONE_DATA ADD (MODIFY_DATE DATE DEFAULT SYSDATE);                   
